-- Notifications
-- naughty.connect_signal("request::display", function(n)
--     naughty.layout.box {
-- 		notification = n,
-- 		type = "notification",
-- 		bg = "#4343434",
--         buttons = gears.table.join(
--             awful.button({ }, 2, function()
--                 naughty.notify { preset = naughty.config.presets.critical, title = "could not get other screen" }
--                 -- n:destroy_all_notifications(nil, -1)
--             end)),
--         -- widget_template = {
        --     {
        --         {
        --             naughty.widget.title,
        --             forced_height = dpi(20),
        --             layout = wibox.layout.align.horizontal
        --         },
        --         left = dpi(15),
        --         right = dpi(15),
        --         top = dpi(10),
        --         bottom = dpi(10),
        --         widget = wibox.container.margin
        --     },
        --     bg = color.background_dark,
        --     widget = wibox.container.background
        -- }
		-- widget_template = {
		-- 	{
		-- 		{
		-- 			{
		-- 				{
		-- 					{
		-- 						{
		-- 							naughty.widget.title,
		-- 							font = "Ubuntu Nerd Font Bold 14",
		-- 							forced_height = dpi(20),
		-- 							layout = wibox.layout.align.horizontal
		-- 						},
		-- 						left = dpi(15),
		-- 						right = dpi(15),
		-- 						top = dpi(10),
		-- 						bottom = dpi(10),
		-- 						widget = wibox.container.margin
		-- 					},
		-- 					bg = color.background_dark,
		-- 					widget = wibox.container.background
		-- 				},
		-- 				strategy = "min",
		-- 				width = dpi(300),
		-- 				widget = wibox.container.constraint
		-- 			},
		-- 			strategy = "max",
		-- 			width = dpi(400),
		-- 			widget = wibox.container.constraint
		-- 		},
		-- 		{
		-- 			{
		-- 				{
		-- 					{
		-- 						resize_strategy = 'center',
		-- 						widget = naughty.widget.icon or
		-- 							os.getenv("HOME") .. '/.config/awesome/deco/icons/notif.png'
		-- 					},
		-- 					margins       = beautiful.notification_margin,
		-- 					widget        = wibox.container.margin,
		-- 					forced_height = dpi(70),
		-- 					forced_width  = dpi(100),
		-- 					top           = dpi(10),
		-- 					bottom        = dpi(10),
		-- 					left          = dpi(15),
		-- 					right         = dpi(10)
		-- 				},
		-- 				widget = wibox.container.background,
		-- 				bg = color.background_lighter

		-- 			},
		-- 			{
		-- 				{
		-- 					{
		-- 						naughty.widget.message,
		-- 						left = dpi(15),
		-- 						right = dpi(15),
		-- 						top = dpi(10),
		-- 						bottom = dpi(10),
		-- 						widget = wibox.container.margin
		-- 					},
		-- 					strategy = "min",
		-- 					height = dpi(60),
		-- 					widget = wibox.container.constraint
		-- 				},
		-- 				strategy = "max",
		-- 				width = dpi(400),
		-- 				widget = wibox.container.constraint
		-- 			},
		-- 			layout = wibox.layout.align.horizontal
		-- 		},
		-- 		{
		-- 			actions_template,
		-- 			widget = wibox.container.margin,
		-- 			top = 0,
		-- 			bottom = 5,
		-- 			left = 10,
		-- 			right = 10
		-- 		},
		-- 		layout = wibox.layout.align.vertical
		-- 	},
		-- 	id = "background_role",
		-- 	widget = naughty.container.background,
		-- 	bg = color.background_lighter
		-- }
-- 	}

-- end)
-- naughty.connect_signal("request::display", function (n)
	-- Main container of the notification
	-- local container = wibox.widget{
	-- 	spacing = beautiful.notification_margin,
	-- 	layout = wibox.layout.fixed.vertical
	-- }

	-- local icon = wibox.widget{
	-- 	resize_strategy = "scale",
	-- 	widget = naughty.widget.icon
	-- }

	-- local app_icon = function ()
	-- 	local widget = {}

	-- 	if not n.app_icon == nil  or not n.app_icon == '' then
	-- 		widget = wibox.widget{
	-- 			image = n.app_icon,
	-- 			resize = true,
	-- 			forced_height = dpi(16),
	-- 			forced_width = dpi(16),
	-- 			widget = wibox.widget.imagebox
	-- 		}
	-- 	elseif not n.image == nil or not n.image == '' then
	-- 		widget = wibox.widget{
	-- 			image = n.image,
	-- 			resize = true,
	-- 			forced_height = dpi(16),
	-- 			forced_width = dpi(16),
	-- 			widget = wibox.widget.imagebox
	-- 		}

	-- 	else
	-- 		widget = nil
	-- 	end

	-- 	return widget
	-- end


	-- local dismiss_button = wibox.widget{
	-- 	{
	-- 		{
	-- 			{
	-- 				image = beautiful.icon_times,
	-- 				resize = true,
	-- 				forced_height = dpi(16),
	-- 				forced_width = dpi(16),
	-- 				widget = wibox.widget.imagebox
	-- 			},
	-- 			margins = dpi(1),
	-- 			widget = wibox.container.margin
	-- 		},
	-- 		bg = beautiful.bg_button,
	-- 		border_width = beautiful.btn_border_width,
	-- 		border_color = beautiful.border_button,
	-- 		shape =  gears.shape.circle,
	-- 		widget = wibox.container.background
	-- 	},
	-- 	widget = clickable_container
	-- }

	-- dismiss_button:connect_signal("button::press", function (_,_,_,button)
	-- 	if button == 1 then
	-- 		n:destroy(nil, 1)
	-- 	end
	-- end)

	-- local app_name = wibox.widget{
	-- 	markup = n.app_name or "System Notification",
	-- 	font = "Ubuntu Bold 10",
	-- 	align = 'center',
	-- 	valign = 'center',
	-- 	widget = wibox.widget.textbox
	-- }

	-- local app_icon_with_name_and_dismiss_btn = wibox.widget{
	-- 	{
	-- 		app_icon(),
	-- 		app_name,
	-- 		spacing = beautiful.notification_margin,
	-- 		layout = wibox.layout.fixed.horizontal
	-- 	},
	-- 	nil,
	-- 	dismiss_button,
	-- 	expand = "inside",
	-- 	spacing = beautiful.notification_margin,
	-- 	layout = wibox.layout.align.horizontal
	-- }

	-- local action_list = wibox.widget {
	-- 	notification = n,
	-- 	base_layout = wibox.widget {
	-- 		spacing = beautiful.notification_margin,
	-- 		layout = wibox.layout.fixed.horizontal
	-- 	},
	-- 	widget_template = {
	-- 		{
	-- 			{
	-- 				{
	-- 					id = 'text_role',
	-- 					align = "center",
	-- 					valign = "center",
	-- 					widget = wibox.widget.textbox
	-- 				},
	-- 				top = dpi(4),
	-- 				bottom = dpi(4),
	-- 				left = dpi(10),
	-- 				right = dpi(10),
	-- 				widget = wibox.container.margin
	-- 			},
	-- 			bg = beautiful.bg_button,
	-- 			border_width = beautiful.btn_border_width,
	-- 			border_color = beautiful.border_button,
	-- 			shape = gears.shape.rounded_bar,
	-- 			widget = wibox.container.background,
	-- 		},
	-- 		widget  = clickable_container,
	-- 	},
	-- 	style = { underline_normal = false, underline_selected = true },
	-- 	widget = naughty.list.actions,
	-- }

	-- local title_area_and_message = wibox.widget{
	-- 	naughty.widget.title,
	-- 	naughty.widget.message,
	-- 	spacing = beautiful.notification_margin,
	-- 	layout = wibox.layout.fixed.vertical
	-- }


	-- local notibox = wibox.widget{
	-- 	app_icon_with_name_and_dismiss_btn,
	-- 	{
	-- 		icon,
	-- 		title_area_and_message,
	-- 		spacing = beautiful.notification_margin,
	-- 		layout = wibox.layout.fixed.horizontal
	-- 	},
	-- 	spacing = beautiful.notification_margin,
	-- 	layout = wibox.layout.fixed.vertical
	-- }


	-- naughty.layout.box {
	-- 	notification = n,
	-- 	bg = "#00000000",
	-- 	widget_template = {
	-- 		{
	-- 			{
	-- 				{
	-- 					notibox,
	-- 					action_list,
	-- 					widget = container
	-- 				},
	-- 				margins = beautiful.notification_margin,
	-- 				widget = wibox.container.margin
	-- 			},
	-- 			bg = beautiful.bg_normal,
	-- 			shape = beautiful.widget_shape,
	-- 			widget = wibox.container.background
	-- 		},
	-- 		strategy = "max",
	-- 		forced_width = beautiful.notification_max_width or dpi(300),
    -- 		widget = wibox.container.constraint
	-- 	}
	-- }

	-- local focused = awful.screen.focused()
	-- if _G.dont_disturb or
	-- 	(focused.central_panel and focused.central_panel.visible) then
	-- 	naughty.destroy_all_notifications(nil, 1)
	-- end

-- end)
