    --s.mytasklist = awful.widget.tasklist {
    --screen   = s,
    --filter   = awful.widget.tasklist.filter.currenttags,
    --buttons  = tasklist_buttons,
    --style    = {
    --    shape_border_width = 1,
    --    shape_border_color = '#777777',
    --    shape  = gears.shape.rounded_bar,
    --},
    --layout   = {
    --    spacing = 10,
    --    spacing_widget = {
    --        {
    --            forced_width = 5,
    --            shape        = gears.shape.circle,
    --            widget       = wibox.widget.separator
    --        },
    --        valign = 'center',
    --        halign = 'center',
    --        widget = wibox.container.place,
    --    },
    --    layout  = wibox.layout.flex.horizontal
    --},
    ---- Notice that there is *NO* wibox.wibox prefix, it is a template,
    ---- not a widget instance.
    --widget_template = {
    --    {
    --        {
    --            {
    --                {
    --                    id     = 'icon_role',
    --                    widget = wibox.widget.imagebox,
    --                },
    --                margins = 2,
    --                widget  = wibox.container.margin,
    --            },
    --            {
    --                id     = 'text_role',
    --                widget = wibox.widget.textbox,
    --            },
    --            layout = wibox.layout.fixed.horizontal,
    --        },
    --        left  = 10,
    --        right = 10,
    --        widget = wibox.container.margin
    --    },
    --    id     = 'background_role',
    --    widget = wibox.container.background,
    --  },
    --}

